/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.whiteelephant.parsing;  
@SuppressWarnings("all")
public enum TaskStatus { 
  SUCCESS, FAILED, KILLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TaskStatus\",\"namespace\":\"com.linkedin.whiteelephant.parsing\",\"symbols\":[\"SUCCESS\",\"FAILED\",\"KILLED\"]}");
}
