/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.whiteelephant.analysis;  
@SuppressWarnings("all")
public class AttemptStatsValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AttemptStatsValue\",\"namespace\":\"com.linkedin.whiteelephant.analysis\",\"fields\":[{\"name\":\"started\",\"type\":\"int\"},{\"name\":\"finished\",\"type\":\"int\"},{\"name\":\"elapsedMinutes\",\"type\":\"double\"},{\"name\":\"cpuMinutes\",\"type\":[\"double\",\"null\"]},{\"name\":\"spilledRecords\",\"type\":[\"long\",\"null\"]},{\"name\":\"reduceShuffleBytes\",\"type\":[\"long\",\"null\"]}]}");
  @Deprecated public int started;
  @Deprecated public int finished;
  @Deprecated public double elapsedMinutes;
  @Deprecated public java.lang.Double cpuMinutes;
  @Deprecated public java.lang.Long spilledRecords;
  @Deprecated public java.lang.Long reduceShuffleBytes;

  /**
   * Default constructor.
   */
  public AttemptStatsValue() {}

  /**
   * All-args constructor.
   */
  public AttemptStatsValue(java.lang.Integer started, java.lang.Integer finished, java.lang.Double elapsedMinutes, java.lang.Double cpuMinutes, java.lang.Long spilledRecords, java.lang.Long reduceShuffleBytes) {
    this.started = started;
    this.finished = finished;
    this.elapsedMinutes = elapsedMinutes;
    this.cpuMinutes = cpuMinutes;
    this.spilledRecords = spilledRecords;
    this.reduceShuffleBytes = reduceShuffleBytes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return started;
    case 1: return finished;
    case 2: return elapsedMinutes;
    case 3: return cpuMinutes;
    case 4: return spilledRecords;
    case 5: return reduceShuffleBytes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: started = (java.lang.Integer)value$; break;
    case 1: finished = (java.lang.Integer)value$; break;
    case 2: elapsedMinutes = (java.lang.Double)value$; break;
    case 3: cpuMinutes = (java.lang.Double)value$; break;
    case 4: spilledRecords = (java.lang.Long)value$; break;
    case 5: reduceShuffleBytes = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'started' field.
   */
  public java.lang.Integer getStarted() {
    return started;
  }

  /**
   * Sets the value of the 'started' field.
   * @param value the value to set.
   */
  public void setStarted(java.lang.Integer value) {
    this.started = value;
  }

  /**
   * Gets the value of the 'finished' field.
   */
  public java.lang.Integer getFinished() {
    return finished;
  }

  /**
   * Sets the value of the 'finished' field.
   * @param value the value to set.
   */
  public void setFinished(java.lang.Integer value) {
    this.finished = value;
  }

  /**
   * Gets the value of the 'elapsedMinutes' field.
   */
  public java.lang.Double getElapsedMinutes() {
    return elapsedMinutes;
  }

  /**
   * Sets the value of the 'elapsedMinutes' field.
   * @param value the value to set.
   */
  public void setElapsedMinutes(java.lang.Double value) {
    this.elapsedMinutes = value;
  }

  /**
   * Gets the value of the 'cpuMinutes' field.
   */
  public java.lang.Double getCpuMinutes() {
    return cpuMinutes;
  }

  /**
   * Sets the value of the 'cpuMinutes' field.
   * @param value the value to set.
   */
  public void setCpuMinutes(java.lang.Double value) {
    this.cpuMinutes = value;
  }

  /**
   * Gets the value of the 'spilledRecords' field.
   */
  public java.lang.Long getSpilledRecords() {
    return spilledRecords;
  }

  /**
   * Sets the value of the 'spilledRecords' field.
   * @param value the value to set.
   */
  public void setSpilledRecords(java.lang.Long value) {
    this.spilledRecords = value;
  }

  /**
   * Gets the value of the 'reduceShuffleBytes' field.
   */
  public java.lang.Long getReduceShuffleBytes() {
    return reduceShuffleBytes;
  }

  /**
   * Sets the value of the 'reduceShuffleBytes' field.
   * @param value the value to set.
   */
  public void setReduceShuffleBytes(java.lang.Long value) {
    this.reduceShuffleBytes = value;
  }

  /** Creates a new AttemptStatsValue RecordBuilder */
  public static com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder newBuilder() {
    return new com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder();
  }
  
  /** Creates a new AttemptStatsValue RecordBuilder by copying an existing Builder */
  public static com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder newBuilder(com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder other) {
    return new com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder(other);
  }
  
  /** Creates a new AttemptStatsValue RecordBuilder by copying an existing AttemptStatsValue instance */
  public static com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder newBuilder(com.linkedin.whiteelephant.analysis.AttemptStatsValue other) {
    return new com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder(other);
  }
  
  /**
   * RecordBuilder for AttemptStatsValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AttemptStatsValue>
    implements org.apache.avro.data.RecordBuilder<AttemptStatsValue> {

    private int started;
    private int finished;
    private double elapsedMinutes;
    private java.lang.Double cpuMinutes;
    private java.lang.Long spilledRecords;
    private java.lang.Long reduceShuffleBytes;

    /** Creates a new Builder */
    private Builder() {
      super(com.linkedin.whiteelephant.analysis.AttemptStatsValue.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing AttemptStatsValue instance */
    private Builder(com.linkedin.whiteelephant.analysis.AttemptStatsValue other) {
            super(com.linkedin.whiteelephant.analysis.AttemptStatsValue.SCHEMA$);
      if (isValidValue(fields()[0], other.started)) {
        this.started = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.started);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.finished)) {
        this.finished = (java.lang.Integer) data().deepCopy(fields()[1].schema(), other.finished);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.elapsedMinutes)) {
        this.elapsedMinutes = (java.lang.Double) data().deepCopy(fields()[2].schema(), other.elapsedMinutes);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cpuMinutes)) {
        this.cpuMinutes = (java.lang.Double) data().deepCopy(fields()[3].schema(), other.cpuMinutes);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.spilledRecords)) {
        this.spilledRecords = (java.lang.Long) data().deepCopy(fields()[4].schema(), other.spilledRecords);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.reduceShuffleBytes)) {
        this.reduceShuffleBytes = (java.lang.Long) data().deepCopy(fields()[5].schema(), other.reduceShuffleBytes);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'started' field */
    public java.lang.Integer getStarted() {
      return started;
    }
    
    /** Sets the value of the 'started' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder setStarted(int value) {
      validate(fields()[0], value);
      this.started = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'started' field has been set */
    public boolean hasStarted() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'started' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder clearStarted() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'finished' field */
    public java.lang.Integer getFinished() {
      return finished;
    }
    
    /** Sets the value of the 'finished' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder setFinished(int value) {
      validate(fields()[1], value);
      this.finished = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'finished' field has been set */
    public boolean hasFinished() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'finished' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder clearFinished() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'elapsedMinutes' field */
    public java.lang.Double getElapsedMinutes() {
      return elapsedMinutes;
    }
    
    /** Sets the value of the 'elapsedMinutes' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder setElapsedMinutes(double value) {
      validate(fields()[2], value);
      this.elapsedMinutes = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'elapsedMinutes' field has been set */
    public boolean hasElapsedMinutes() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'elapsedMinutes' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder clearElapsedMinutes() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'cpuMinutes' field */
    public java.lang.Double getCpuMinutes() {
      return cpuMinutes;
    }
    
    /** Sets the value of the 'cpuMinutes' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder setCpuMinutes(java.lang.Double value) {
      validate(fields()[3], value);
      this.cpuMinutes = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'cpuMinutes' field has been set */
    public boolean hasCpuMinutes() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'cpuMinutes' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder clearCpuMinutes() {
      cpuMinutes = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'spilledRecords' field */
    public java.lang.Long getSpilledRecords() {
      return spilledRecords;
    }
    
    /** Sets the value of the 'spilledRecords' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder setSpilledRecords(java.lang.Long value) {
      validate(fields()[4], value);
      this.spilledRecords = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'spilledRecords' field has been set */
    public boolean hasSpilledRecords() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'spilledRecords' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder clearSpilledRecords() {
      spilledRecords = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'reduceShuffleBytes' field */
    public java.lang.Long getReduceShuffleBytes() {
      return reduceShuffleBytes;
    }
    
    /** Sets the value of the 'reduceShuffleBytes' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder setReduceShuffleBytes(java.lang.Long value) {
      validate(fields()[5], value);
      this.reduceShuffleBytes = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'reduceShuffleBytes' field has been set */
    public boolean hasReduceShuffleBytes() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'reduceShuffleBytes' field */
    public com.linkedin.whiteelephant.analysis.AttemptStatsValue.Builder clearReduceShuffleBytes() {
      reduceShuffleBytes = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public AttemptStatsValue build() {
      try {
        AttemptStatsValue record = new AttemptStatsValue();
        record.started = fieldSetFlags()[0] ? this.started : (java.lang.Integer) defaultValue(fields()[0]);
        record.finished = fieldSetFlags()[1] ? this.finished : (java.lang.Integer) defaultValue(fields()[1]);
        record.elapsedMinutes = fieldSetFlags()[2] ? this.elapsedMinutes : (java.lang.Double) defaultValue(fields()[2]);
        record.cpuMinutes = fieldSetFlags()[3] ? this.cpuMinutes : (java.lang.Double) defaultValue(fields()[3]);
        record.spilledRecords = fieldSetFlags()[4] ? this.spilledRecords : (java.lang.Long) defaultValue(fields()[4]);
        record.reduceShuffleBytes = fieldSetFlags()[5] ? this.reduceShuffleBytes : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
