/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.whiteelephant.analysis;  
@SuppressWarnings("all")
public enum TimeUnit { 
  HOURS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TimeUnit\",\"namespace\":\"com.linkedin.whiteelephant.analysis\",\"symbols\":[\"HOURS\"]}");
}
